<?php

// phpcs:disable Yoast.NamingConventions.NamespaceName.TooLong
namespace Yoast\WP\SEO\Llms_Txt\Application\Markdown_Builders;

use Yoast\WP\SEO\Llms_Txt\Domain\Markdown\Sections\Intro;

/**
 * The builder of the intro section.
 */
class Intro_Builder {

	/**
	 * Gets the plugin version that generated the llms.txt file.
	 *
	 * @return string The plugin version that generated the llms.txt file.
	 */
	protected function get_generator_version(): string {
		return 'Yoast SEO v' . \WPSEO_VERSION;
	}

	/**
	 * Builds the intro section.
	 *
	 * @return Intro The intro section.
	 */
	public function build_intro(): Intro {
		$intro_content = \sprintf(
			'Generated by %s, this is an llms.txt file, meant for consumption by LLMs.',
			$this->get_generator_version()
		);

<<<<<<< HEAD
		$sitemap_link = $this->sitemap_link_collector->get_link();
		if ( $sitemap_link !== null ) {
			$intro_links[] = $sitemap_link;

			$intro_content .= \PHP_EOL . \PHP_EOL . 'The XML sitemap of this website can be found by following %s.';
		}

		return new Intro( $intro_content, $intro_links );
=======
		return new Intro( $intro_content, [] );
>>>>>>> 07955227f67d14ec4798c4b901c136b69715eefe
	}
}
